pipeline:
  name: build
  identifier: build
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build and Deploy
        identifier: Build_And_Deploy
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Checkout Code
                  identifier: Checkout_Code
                  type: ShellScript
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Cloning repo..."
                          rm -rf helloservice
                          git clone https://github.com/DatlaBharath/helloservice.git
                          cd helloservice
                          pwd
                          ls
                    executionTarget: {}
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
