pipeline:
  name: build
  identifier: build
  stages:
    - stage:
        name: Checkout
        identifier: checkout
        steps:
          - step:
              type: Script
              name: Clone Git Repository
              identifier: clone_repo
              spec:
                shell: Bash
                onDelegate: true
                executionTarget: {}
                environmentVariables: {}
                outputVariables: []
                command: |-
                  git clone https://github.com/DatlaBharath/helloservice.git
    - stage:
        name: Build and Push
        identifier: build_and_push
        steps:
          - step:
              type: BuildDockerImages
              name: Build Image
              identifier: build_image
              spec:
                connectorRef: dockerhub
                repository: sakthisiddu1/helloservice
                tags:
                  - "${TAG}"
                buildCommand: |-
                  mvn clean package
          - step:
              type: DockerPush
              name: Push Image to Docker Hub
              identifier: push_docker_image
              spec:
                connectorRef: dockerhub
                repository: sakthisiddu1/helloservice
                tags:
                  - "${TAG}"
    - stage:
        name: Deploy
        identifier: deploy
        steps:
          - step:
              type: SSH
              name: Connect to Instance
              identifier: ssh_connect
              spec:
                host: "13.201.72.36"
                platform: Linux
                authentication:
                  type: SSHKey
                  spec:
                    userName: "ubuntu"
                    keyFile: "/path/to/private/key"
              environmentVariables:
                - APP_PORT: "5000"
                - BRANCH_NAME: "main"
              command: |-
                kubectl apply -f deployment.yaml