pipeline:
  name: build
  identifier: build
  projectIdentifier: default
  orgIdentifier: default
  tags: {}

  stages:
    - stage:
        name: Build Stage
        identifier: Build_Stage
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Print Hello from Delegate
                  identifier: Print_Hello
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "This script runs on the delegate!"
                          echo "Git sync is working perfectly!"
                    environmentVariables: []
                    outputVariables: []
