---
version: 2
plan:
  project-key: JAVA
  name: Maven Build and Docker Deploy Plan
  key: BUILD

stages:
  - Build and Deploy:
      jobs:
        - Build and Package

Build and Package:
  tasks:
    - script:
        - mvn clean install
        - docker build -t helloservice--jenkins:3 .
        - docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin ${{ secrets.DOCKERHUB_PASSWORD }}
        - docker push sakthisiddu1/helloservice--jenkins:3
