---
version: 2
plan:
  project-key: JAVA
  name: Maven Build and Docker Deploy Plan
  key: BUILD

stages:
  - Build and Deploy:
      jobs:
        - Build and Package

Build and Package:
  tasks:
    - script:
        - mvn clean install
        - docker build -t helloservice-jenkins:latest .
        - docker login -u ${bamboo.dockerUsername} --password-stdin ${bamboo.dockerPassword}
        - docker push sakthisiddu1/helloservice-jenkins:latest
