---
version: 2
plan:
  project-key: JAVA
  name: Maven Build and Docker Deploy Plan
  key: BUILD

stages:
  - Build and Deploy:
      jobs:
        - Maven Build
        - Docker Build
        - Docker Push

Maven Build:
  tasks:
    - script:
        - mvn clean install

Docker Build:
  tasks:
    - script:
        - docker build -t helloservice-jenkins:latest .

Docker Push:
  tasks:
    - script:
        - echo "${bamboo.DOCKER_PASSWORD}" | docker login -u "${bamboo.DOCKER_USERNAME}" --password-stdin
        - docker push sakthisiddu1/helloservice-jenkins:latest
  environment:
    DOCKER_USERNAME: sakthisiddu1
    DOCKER_PASSWORD: Sakthisid@1
