---
version: 2
plan:
  project-key: JAVA
  name: Maven Build and Docker Deploy Plan
  key: BUILD

stages:
  - Build and Deploy:
      jobs:
        - Build and Package

Build and Package:
  tasks:
    - script:
        - mvn clean install
        - docker build -t sakthisiddu1/helloservice:3 .
        - echo "Sakthisid@1" | docker login -u sakthisiddu1 --password-stdin --password-stdin
        - docker push sakthisiddu1/helloservice:3
