version: 2
plan:
  project-key: "PROJ"        # Replace with your Bamboo project key
  key: "BUILD"               # Replace with your plan key (unique identifier for this plan)
  name: "Maven Build Plan"   # The name of your build plan
stages:
  - Build hull:
    - Build
 
Build:
  tasks:
    - script:
      - echo 'Hello World!!!!'
