---
version: 2
plan:
  project-key: JAVA
  name: Maven Build and Docker Deploy Plan
  key: BUILD

stages:
  - Build and Deploy:
      jobs:
        - Maven Build
        

Maven Build:
  tasks:
    - script:
        - mvn clean install


