version: 2
plan:
  key: HEL
  name: Hello Bamboo Plan
  description: This plan checks out code, builds the project, and creates a Docker image.
  project-key: HELLO
  repository:
    type: git
    url: https://github.com/DatlaBharath/HelloService
    branch: master

stages:
  - Build:
      jobs:
        - Build:
            tasks:
              - checkout:
                  clean-build: true
              - maven:
                  goals: clean install
              - docker:
                  image: hello-bamboo:latest
                  command: build -t hello-bamboo:latest .
