name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_project:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven (if not already installed)
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Build the project
        run: mvn clean install -DskipTests

  build_image:
    needs: build_project
    runs-on: self-hosted
    steps:
      - name: Build Docker image
        run: docker build -t sakthisiddu1/helloservice:${{ github.run_number }} .

  push_image:
    needs: build_image
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push sakthisiddu1/helloservice:${{ github.run_number }}

  deploy:
    needs: push_image
    runs-on: self-hosted
    steps:
      - name: Create and apply Kubernetes Deployment
        run: |
          echo "
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: helloservice-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: helloservice
            template:
              metadata:
                labels:
                  app: helloservice
              spec:
                containers:
                - name: helloservice
                  image: sakthisiddu1/helloservice:${{ github.run_number }}
                  ports:
                  - containerPort: 5000
          " > deployment.yaml

          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@13.232.68.7 "kubectl apply -f -" < deployment.yaml
          
      - name: Create and apply Kubernetes Service
        run: |
          echo "
          apiVersion: v1
          kind: Service
          metadata:
            name: helloservice-service
          spec:
            selector:
              app: helloservice
            type: NodePort
            ports:
              - protocol: TCP
                port: 5000
                targetPort: 5000
                nodePort: 30007
          " > service.yaml

          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@13.232.68.7 "kubectl apply -f -" < service.yaml