name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  curl_request:
    runs-on: self-hosted
    steps:
      - name: Execute CURL request and capture response
        id: curl_response
        run: |
          # Capture the response from the original API
          response=$(curl -s http://ec2-13-201-18-57.ap-south-1.compute.amazonaws.com/app/random-data)
          
          # Log the response in GitHub Actions log
          echo "Curl response: $response"
          curl -X POST http://ec2-13-201-18-57.ap-south-1.compute.amazonaws.com/app/save-curl-response \
            -H "Content-Type: application/json" \
            -d '{"response": \"$response\"}'
          # Check if the response contains 'success': true (example)
          if [[ "$response" == *'"success":true'* ]]; then
            echo "Success response received."
            echo "status=true" >> $GITHUB_ENV
          else
            echo "Failure response received."
            echo "status=false" >> $GITHUB_ENV
          fi
          # Send the response to your backend to be stored in a file
          
