name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Build Docker Image
      run: docker build -t sakthisiddu1/helloservice:${{ github.run_number }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker Image
      run: docker push sakthisiddu1/helloservice:${{ github.run_number }}

    - name: Set up K8s
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Deploy to Kubernetes
      run: |
        echo "
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: helloservice-deployment
          labels:
            app: helloservice
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: helloservice
          template:
            metadata:
              labels:
                app: helloservice
            spec:
              containers:
              - name: helloservice
                image: sakthisiddu1/helloservice:${{ github.run_number }}
                ports:
                - containerPort: 5000
        " > deployment.yaml

        echo "
        apiVersion: v1
        kind: Service
        metadata:
          name: helloservice-service
        spec:
          selector:
            app: helloservice
          ports:
          - protocol: TCP
            port: 5000
            targetPort: 5000
            nodePort: 30007
          type: NodePort
        " > service.yaml

        ssh -i /home/ubuntu/.ssh/test.pem -o StrictHostKeyChecking=no ubuntu@13.203.9.97 "kubectl apply -f -" < deployment.yaml
        ssh -i /home/ubuntu/.ssh/test.pem -o StrictHostKeyChecking=no ubuntu@13.203.9.97 "kubectl apply -f -" < service.yaml

    - name: Post Success
      if: success()
      run: echo 'Deployment was successful'

    - name: Post Failure
      if: failure()
      run: echo 'Deployment failed'