name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_project:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven (if not already installed)
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Build with Maven
        run: |
          mvn clean install -DskipTests

  build_image:
    runs-on: self-hosted
    needs: build_project
    steps:
      - name: Build Docker Image
        run: |
          TAG=${GITHUB_RUN_NUMBER}
          docker build -t sakthisiddu1/helloservice:$TAG .

  push_image:
    runs-on: self-hosted
    needs: build_image
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          TAG=${GITHUB_RUN_NUMBER}
          docker push sakthisiddu1/helloservice:$TAG

  deploy:
    runs-on: self-hosted
    needs: push_image
    steps:
      - name: Create Kubernetes Deployment and Service YAML
        run: |
          TAG=${GITHUB_RUN_NUMBER}
          echo "
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-service
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: hello
            template:
              metadata:
                labels:
                  app: hello
              spec:
                containers:
                - name: hello
                  image: sakthisiddu1/helloservice:$TAG
                  ports:
                  - containerPort: 5000
          " > deployment.yaml

          echo "
          apiVersion: v1
          kind: Service
          metadata:
            name: hello-service
          spec:
            type: NodePort
            selector:
              app: hello
            ports:
              - protocol: TCP
                port: 5000
                targetPort: 5000
                nodePort: 30007
          " > service.yaml

      - name: Deploy to Kubernetes
        run: |
          TAG=${GITHUB_RUN_NUMBER}
          scp -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem deployment.yaml ubuntu@3.6.92.160:/home/ubuntu/deployment.yaml
          scp -i /home/ubuntu/.ssh/test.pem -o StrictHostKeyChecking=no service.yaml ubuntu@3.6.92.160:/home/ubuntu/service.yaml
          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@3.6.92.160 "kubectl apply -f /home/ubuntu/deployment.yaml"
          ssh -i /home/ubuntu/.ssh/test.pem -o StrictHostKeyChecking=no ubuntu@3.6.92.160 "kubectl apply -f /home/ubuntu/service.yaml"