name: Migrate from Jenkins to GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up custom Java package
      run: |
        download_url="https://example.com/java/jdk/6u45-b06/jdk-6u45-linux-x64.tar.gz"
        wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
    - uses: actions/setup-java@v4
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/java_package.tar.gz
        java-version: '1.6'
        architecture: x64

    - name: Set up multiple JDKs
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          8
          11

    - name: Set up Java 15
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '15'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test