name: Migrate from Jenkins to GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Hello World
      run: echo 'Hello, World!'

    - name: Write and Cat File
      run: |
        echo "Hello from Jenkins" > hello.txt
        cat hello.txt