name: CI/CD Pipeline

on:
  push:
    branches: 
      - main

jobs:
  build_project:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven (if not already installed)
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

  build_image:
    runs-on: self-hosted
    needs: build_project

    steps:
      - name: Build Docker image
        run: docker build -t sakthisiddu1/helloservice:${{ github.run_number }} .

  push_image:
    runs-on: self-hosted
    needs: build_image

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push sakthisiddu1/helloservice:${{ github.run_number }}

  deploy:
    runs-on: self-hosted
    needs: push_image

    steps:
      - name: Create Deployment YAML
        run: |
          echo "
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: helloservice-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: helloservice
            template:
              metadata:
                labels:
                  app: helloservice
              spec:
                containers:
                - name: helloservice
                  image: sakthisiddu1/helloservice:${{ github.run_number }}
                  ports:
                  - containerPort: 5000
          " > deployment.yaml
                
      - name: Create Service YAML
        run: |
          echo "
          apiVersion: v1
          kind: Service
          metadata:
            name: helloservice-service
          spec:
            type: NodePort
            selector:
              app: helloservice
            ports:
            - protocol: TCP
              port: 80
              targetPort: 5000
              nodePort: 30007
          " > service.yaml

      - name: Deploy to Kubernetes
        run: |
          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@13.235.19.87 "kubectl apply -f -" < deployment.yaml
          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@13.235.19.87 "kubectl apply -f -" < service.yaml