name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'maven'
        maven-version: '3.6.3'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Build Docker image
      run: docker build -t sakthisiddu1/helloservice:${{ github.run_number }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      run: docker push sakthisiddu1/helloservice:${{ github.run_number }}

    - name: Generate Kubernetes deployment YAML
      run: |
        echo "apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: helloservice-deployment
          labels:
            app: helloservice
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: helloservice
          template:
            metadata:
              labels:
                app: helloservice
            spec:
              containers:
              - name: helloservice
                image: sakthisiddu1/helloservice:${{ github.run_number }}
                ports:
                - containerPort: 5000" > deployment.yaml

    - name: Generate Kubernetes service YAML
      run: |
        echo "apiVersion: v1
        kind: Service
        metadata:
          name: helloservice-service
        spec:
          selector:
            app: helloservice
          ports:
          - protocol: TCP
            port: 5000
            targetPort: 5000
            nodePort: 30007
          type: NodePort" > service.yaml

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Deploy to Kubernetes
      run: |
        scp -i /home/ubuntu/.ssh/test.pem -o StrictHostKeyChecking=no deployment.yaml ubuntu@3.6.238.137:/home/ubuntu/
        scp -i /home/ubuntu/.ssh/test.pem -o StrictHostKeyChecking=no service.yaml ubuntu@3.6.238.137:/home/ubuntu/
        ssh -i /home/ubuntu/.ssh/test.pem -o StrictHostKeyChecking=no ubuntu@13.203.9.97 "kubectl apply -f /home/ubuntu/deployment.yaml"
        ssh -i /home/ubuntu/.ssh/test.pem -o StrictHostKeyChecking=no ubuntu@13.203.9.97 "kubectl apply -f /home/ubuntu/service.yaml"

    - name: Deployment success message
      if: success()
      run: echo 'Deployment was successful'

    - name: Deployment failure message
      if: failure()
      run: echo 'Deployment failed'