name: Migrate from Jenkins

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run shell command
        run: echo "hello world"

      - name: Post success
        if: success()
        run: echo "Build succeeded"

      - name: Post failure
        if: failure()
        run: echo "Build failed"