name: Basic Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: 'H/5 * * * *'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm
          cache-dependency-path:
            - server/app/package-lock.json
            - frontend/app/package-lock.json

      - name: List directory contents
        run: ls