name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: echo 'Building project'

      - name: Test
        run: echo 'Testing'

      - name: Deploy
        run: echo 'Deploying'

      - name: Deployment Success
        if: success()
        run: echo 'Deployment success'

      - name: Deployment Failure
        if: failure()
        run: echo 'Deployment failed'