name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Running Maven clean install
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t sakthisiddu1/helloservice:${{ github.run_number }} .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push sakthisiddu1/helloservice:${{ github.run_number }}

      - name: Process completed successfully
        if: success()
        run: echo "Process completed successfully!"

      - name: Process failed
        if: failure()
        run: echo "Process failed!"