name: Basic Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: List directory contents
        run: ls
