name: Test GitHub PAT Token

on: [push]

jobs:
  test-token:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub PAT Token
        run: echo "PAT_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV

      - name: Test Token with curl (safe)
        run: |
          curl -H "Authorization: Bearer $PAT_TOKEN" https://api.github.com/user
