name: Pipeline with User Confirmation

on:
  workflow_dispatch:
    inputs:
      proceed_after_stage1:
        description: 'Proceed to next stages after Stage 1?'
        required: true
        default: 'false'
        type: boolean

jobs:
  stage1:
    name: Stage 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Stage 1 tasks
        run: echo "Running Stage 1 tasks"
        
      - name: Stage 1 completed - check input value
        run: |
          if [ "${{ github.event.inputs.proceed_after_stage1 }}" == "true" ]; then
            echo "Will proceed to next stages"
          else
            echo "Will stop after this stage"
          fi

  stage2:
    name: Stage 2
    needs: stage1
    if: ${{ github.event.inputs.proceed_after_stage1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Stage 2 tasks
        run: echo "Running Stage 2 tasks"

  stage3:
    name: Stage 3
    needs: stage2
    runs-on: ubuntu-latest
    steps:
      - name: Run Stage 3 tasks
        run: echo "Running Stage 3 tasks"

  stage4:
    name: Stage 4
    needs: stage3
    runs-on: ubuntu-latest
    steps:
      - name: Run Stage 4 tasks
        run: echo "Running Stage 4 tasks"

  stage5:
    name: Stage 5
    needs: stage4
    runs-on: ubuntu-latest
    steps:
      - name: Run Stage 5 tasks
        run: echo "Running Stage 5 tasks"
