name: Debug Secrets
on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Verify Secret Existence
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        # Check if the secret is set
        if [ -z "$DOCKERHUB_USERNAME" ]; then
          echo "DOCKERHUB_USERNAME secret is not set!"
          exit 1
        else
          echo "DOCKERHUB_USERNAME is set"
          # Optionally, print length (not the actual value)
          echo "Secret length: ${#DOCKERHUB_USERNAME}"
        fi

    - name: Detailed Secret Debug
      run: |
        # This will only print if secret exists, helps verify
        echo "Secret first character: ${DOCKERHUB_USERNAME:0:1}"
