name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_project:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Maven (if not already installed)
        run: |
          sudo apt update
          sudo apt install -y maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

  build_image:
    runs-on: self-hosted
    needs: build_project
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t sakthisiddu1/helloservice:${{ github.run_number }} .

  push_image:
    runs-on: self-hosted
    needs: build_image
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image to DockerHub
        run: docker push sakthisiddu1/helloservice:${{ github.run_number }}

  deploy:
    runs-on: self-hosted
    needs: push_image
    steps:
      - name: Generate deployment.yaml
        run: |
          echo "
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: helloservice-deployment
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: helloservice
            template:
              metadata:
                labels:
                  app: helloservice
              spec:
                containers:
                - name: helloservice
                  image: sakthisiddu1/helloservice:${{ github.run_number }}
                  ports:
                  - containerPort: 5000
          " > deployment.yaml
      - name: Generate service.yaml
        run: |
          echo "
          apiVersion: v1
          kind: Service
          metadata:
            name: helloservice-service
          spec:
            selector:
              app: helloservice
            ports:
              - protocol: TCP
                port: 5000
                targetPort: 5000
                nodePort: 30007  
            type: NodePort
          " > service.yaml
      - name: Apply Kubernetes Deployment
        run: |
          ssh -i /var/test.pem -o StrictHostKeyChecking=no ubuntu@3.109.132.27 "kubectl apply -f -" < deployment.yaml
      - name: Apply Kubernetes Service
        run: |
          ssh -i /var/test.pem -o StrictHostKeyChecking=no ubuntu@3.109.132.27 "kubectl apply -f -" < service.yaml
