name: Build and Deploy

on: 
  push:
    branches: 
      - main

jobs:
  build_project:
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install Maven
        run: sudo apt install -y maven
      
      - name: Build with Maven
        run: mvn install -DskipTests

  build_docker_image:
    needs: build_project
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t sakthisiddu1/helloservice:${{ github.run_number }} .
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Push Docker image
        run: docker push sakthisiddu1/helloservice:${{ github.run_number }}
